apiVersion: v2
name: ree
description: Norway real estate price estimator (API + retraining CronJob)
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: rabbitmq
    version: "14.7.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: minio
    version: "14.5.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
  - name: redis
    version: "19.6.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
