api:
  replicaCount: 1

minio:
  enabled: false
  useHelmDependency: false

training:
  enabled: true
  rolling:
    dryRun: false

rabbitmq:
  enabled: true
  fullnameOverride: ""
  auth:
    username: guest
    password: ""
    erlangCookie: ""

redis:
  enabled: true
  fullnameOverride: ""
  auth:
    enabled: true
    password: ""

worker:
  enabled: true
  replicaCount: 1
  queues: "celery,training"

workerTraining:
  enabled: true
  replicaCount: 1
  queue: "training"
