env: kind
logLevel: INFO

image:
  repository: ree
  tag: dev
  pullPolicy: IfNotPresent

secrets:
  name: ree-secrets

api:
  replicaCount: 1

minio:
  enabled: true
  useHelmDependency: false

s3:
  endpoint: http://ree-minio:9000
  secure: false
  region: eu-north-1
  bucketModels: ree-models
  bucketSnapshots: ree-snapshots

training:
  enabled: true
  suspend: true
  schedule: "0 2 1 * *"
  timezone: "Europe/Oslo"
  backoffLimit: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  rolling:
    dryRun: false

rabbitmq:
  enabled: true
  fullnameOverride: ""
  auth:
    username: guest
    password: ""
    erlangCookie: ""

redis:
  enabled: true
  fullnameOverride: ""
  auth:
    enabled: true
    password: ""

worker:
  enabled: true
  replicaCount: 1
  queues: "celery,training"

workerTraining:
  enabled: true
  replicaCount: 1
  queue: "training"
